import { whatsappHref } from './whatsapp';

export const PLANS = [
  {
    id: 'start',
    name: 'START',
    price: 'R$99,90',
    period: '/mês',
    accent: 'var(--accent)',
    tagline: 'A porta de entrada para automação inteligente.',
    subtag: 'Ativação em 48h · cancela quando quiser',
    features: [
      '1 canal ativo (WhatsApp ou Instagram)',
      '1 funil de atendimento estruturado',
      '1 integração configurada',
      'Lê áudios e responde com naturalidade',
      'Atende com texto, imagem e vídeo',
      'Responde comentários e puxa pro direct',
      'Envia link de pagamento no momento certo',
      'Agendamentos automáticos',
      'Base de clientes sempre crescendo',
      'Planilha CRM (origem, status, funil)',
      'Comportamento humanizado (digitando/visualizando)',
      'Memória + Anthropic para respostas de alto nível',
    ],
    cta: { label: 'Começar', href: whatsappHref('plans-start') },
    activation: 'Ativação em 48h',
  },
  {
    id: 'pro',
    name: 'PRO',
    price: 'R$197,90',
    period: '/mês',
    accent: 'var(--pro-accent)',
    tagline: 'Para negócios que não podem perder nenhum lead.',
    badge: 'MAIS ESCOLHIDO',
    subtag: 'Ativação em 48h · cancela quando quiser',
    features: [
      'Tudo do Start',
      '2 canais simultâneos (WhatsApp + Instagram)',
      '2 funis (vendas e suporte ao mesmo tempo)',
      '3 integrações (CRM, Google Agenda, planilhas e mais)',
      'Fluxo de reativação automática de leads frios',
      'Relatório semanal de desempenho no WhatsApp',
      'Sequência de follow-up automático configurada',
      'Suporte prioritário (resposta em até 4h)',
      '1 otimização de fluxo por mês incluída',
    ],
    bonuses: ['Script de abordagem ativa personalizado para o seu nicho'],
    cta: { label: 'Assinar Pro', href: whatsappHref('plans-pro') },
    activation: 'Ativação em 48h',
  },
  {
    id: 'obsidian',
    name: 'OBSIDIAN',
    price: 'R$547,90',
    period: '/mês',
    accent: 'var(--obsidian-accent)',
    tagline: 'Para quem constrói um negócio que não para.',
    badge: 'MEMBER',
    vagas: 'VAGAS LIMITADAS',
    subtag: 'Exclusivo · vagas limitadas',
    features: [
      'Tudo do Pro, sem teto',
      'Canais ilimitados (WhatsApp, Instagram, Site, E-mail)',
      'Funis ilimitados (vendas, suporte, onboarding, cobrança, retenção)',
      'Integrações avançadas (ERP, APIs externas, webhooks, CRM próprio)',
      'Base de conhecimento (documentos, tabelas, histórico completo)',
      'IA treinada com a linguagem e persona da marca',
      'Dashboard de métricas em tempo real',
      'Campanha de reativação mensal configurada pela equipe',
      'Reunião mensal de estratégia e otimização',
      'Suporte VIP dedicado (resposta em até 1h)',
      '3 otimizações de fluxo por mês incluídas',
    ],
    bonuses: ['Persona digital da marca criada do zero', 'Mapeamento completo do funil de vendas no onboarding', 'Acesso antecipado a novos recursos', 'Selo OBSIDIAN MEMBER (cliente prioritário)'],
    cta: { label: 'Entrar', href: whatsappHref('plans-obsidian') },
    activation: 'Exclusivo',
  },
] as const;

export const PLANS_FOOTER = 'Valores base; mídia, hospedagem, licenças e terceiros à parte. Projeto 100% personalizado conforme escopo.';
